[package]
authors = ["Kevin Darlington <kevin@londontrustmedia.com>"]
name = "issueboss"
version = "0.1.0"

[dependencies]
pulldown-cmark = "0.1.2"
structopt = "0.2.3"
toml_edit = "0.1.1"
yansi = "0.4.0"
